chmod: Setup the Infra pipeline.

diff --git a/.github/workflows/frontend-ci-cd.yml b/.github/workflows/frontend-ci-cd.yml
--- a/.github/workflows/frontend-ci-cd.yml
+++ b/.github/workflows/frontend-ci-cd.yml
@@ -3,8 +3,12 @@ name: Frontend CI/CD Pipeline to AWS
 on:
   push:
     branches: [main, staging, clean]
+    paths:
+      - "frontend/**"
   pull_request:
     branches: [staging]
+    paths:
+      - "frontend/**"
 
 jobs:
   build:
@@ -18,6 +22,8 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -29,10 +35,15 @@ jobs:
           cd frontend/
           npm install
 
-      # - name: Scan code for exposed secrets
+      - name: Scan code for exposed secrets
+        uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Check logic vulnerabilities with CodeQL
       #   uses: github/codeql-action/analyze@v2
       #   with:
-      #     category: "secret-scanning"
+      #       category: "secret-scanning"
 
       - name: Build frontend app
         run: |
@@ -77,21 +88,21 @@ jobs:
         run: |
           aws s3 sync . s3://${{ secrets.BUCKET_NAME }} --delete
 
-  cleanup:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push' && github.ref == 'refs/heads/clean'
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # cleanup:
+  #   runs-on: ubuntu-latest
+  #   if: github.event_name == 'push' && github.ref == 'refs/heads/clean'
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up AWS CLI
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: "eu-west-2"
+  #     - name: Set up AWS CLI
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: "eu-west-2"
 
-      - name: Clean up resources
-        run: |
-          aws s3 rm s3://${{ secrets.BUCKET_NAME }} --recursive || echo "S3 bucket might not exist"
-          echo "Cleanup completed."
+  #     - name: Clean up resources
+  #       run: |
+  #         aws s3 rm s3://${{ secrets.BUCKET_NAME }} --recursive || echo "S3 bucket might not exist"
+  #         echo "Cleanup completed."
